// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Booking struct {
	ID        string        `json:"id"`
	Event     *Event        `json:"event"`
	Seat      *Seat         `json:"seat"`
	Status    BookingStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Event struct {
	ID       string       `json:"id"`
	Title    string       `json:"title"`
	StartsAt time.Time    `json:"startsAt"`
	Venue    *Venue       `json:"venue"`
	Seats    []*EventSeat `json:"seats"`
}

type EventSeat struct {
	Seat      *Seat `json:"seat"`
	Available bool  `json:"available"`
}

type Mutation struct {
}

type Query struct {
}

type Seat struct {
	ID      string `json:"id"`
	Section string `json:"section"`
	Row     string `json:"row"`
	Number  int    `json:"number"`
}

type SeatUpdate struct {
	SeatID    string `json:"seatId"`
	Available bool   `json:"available"`
}

type Subscription struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

type Venue struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	City string `json:"city"`
}

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "PENDING"
	BookingStatusConfirmed BookingStatus = "CONFIRMED"
	BookingStatusCancelled BookingStatus = "CANCELLED"
	BookingStatusExpired   BookingStatus = "EXPIRED"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusPending,
	BookingStatusConfirmed,
	BookingStatusCancelled,
	BookingStatusExpired,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusPending, BookingStatusConfirmed, BookingStatusCancelled, BookingStatusExpired:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
